# Generated by Django 4.1.3 on 2022-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_sal',
            field=models.IntegerField(null=True),
        ),
    ]
