# Generated by Django 4.1.3 on 2022-11-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_employee_e_sal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employe',
        ),
    ]
