# Generated by Django 4.1.3 on 2022-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_employee_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
